export interface RetailSeedPreset {
  customerNames: [string, string, string];
  secondCustomerCompany: string;
  customerCities: [string, string, string];
  productNames: [string, string];
  productSkus: [string, string];
  productPrices: [number, number];
  productStocks: [number, number];
  leadTitle: string;
  renewalTitle: string;
  paidInvoiceDescription: string;
  overdueInvoiceDescription: string;
  taskTitles: [string, string];
}

export interface ClinicSeedPreset {
  patientNames: [string, string, string];
  patientCities: [string, string, string];
  patientNote?: string;
  serviceNames: [string, string, string];
  servicePrices: [number, number, number];
  leadTitle: string;
  wonLeadTitle: string;
  reminderTitle: string;
  reminderMessage: string;
}

export interface GeneralSeedPreset {
  firstCustomerName: string;
  firstCustomerCompany: string;
  secondCustomerName: string;
  firstCustomerCity: string;
  secondCustomerCity: string;
  leadTitles: [string, string];
  invoiceDescription: string;
  taskTitles: [string, string];
  invoiceAmount: number;
  paidAmount: number;
}

export const RETAIL_PRESETS: Record<string, RetailSeedPreset> = {
  'demo-retail': {
    customerNames: ['لیلا فرهمند', 'بوتیک ماهان', 'پریسا نادری'],
    secondCustomerCompany: 'ماهان استایل',
    customerCities: ['تهران', 'اصفهان', 'شیراز'],
    productNames: ['مانتو کتی زنانه', 'شلوار جین مردانه'],
    productSkus: ['RT-101', 'RT-202'],
    productPrices: [3200000, 1850000],
    productStocks: [45, 80],
    leadTitle: 'سفارش عمده مانتو پاییزه',
    renewalTitle: 'تمدید قرارداد نمایندگی',
    paidInvoiceDescription: 'مانتو کتی زنانه',
    overdueInvoiceDescription: 'مانتو کتی زنانه — عمده',
    taskTitles: ['انبارگردانی پایان فصل', 'پیگیری بدهی بوتیک ماهان'],
  },
  'demo-supermarket': {
    customerNames: ['خانواده اکبری', 'رستوران گیلاس', 'منصور رفیعی'],
    secondCustomerCompany: 'رستوران گیلاس',
    customerCities: ['تهران', 'تهران', 'کرج'],
    productNames: ['برنج ایرانی ۱۰ کیلویی', 'روغن مایع ۱.۸ لیتری'],
    productSkus: ['SM-110', 'SM-220'],
    productPrices: [2850000, 980000],
    productStocks: [28, 64],
    leadTitle: 'تامین ماهانه اقلام مصرفی ساختمان اداری',
    renewalTitle: 'تمدید سفارش هفتگی رستوران',
    paidInvoiceDescription: 'برنج ایرانی ۱۰ کیلویی',
    overdueInvoiceDescription: 'روغن مایع ۱.۸ لیتری — عمده',
    taskTitles: ['بازبینی سفارش صبحگاهی', 'پیگیری تسویه رستوران گیلاس'],
  },
  'demo-pharmacy': {
    customerNames: ['سمیه شاکری', 'درمانگاه مهر', 'علی موسوی'],
    secondCustomerCompany: 'درمانگاه مهر',
    customerCities: ['تهران', 'تهران', 'ورامین'],
    productNames: ['استامینوفن ۵۰۰', 'شربت سرفه کودکان'],
    productSkus: ['PH-101', 'PH-204'],
    productPrices: [145000, 275000],
    productStocks: [120, 42],
    leadTitle: 'درخواست تامین داروی مصرفی درمانگاه',
    renewalTitle: 'تمدید همکاری تامین ماهانه',
    paidInvoiceDescription: 'استامینوفن ۵۰۰',
    overdueInvoiceDescription: 'شربت سرفه کودکان — عمده',
    taskTitles: ['کنترل اقلام رو به اتمام', 'پیگیری بدهی درمانگاه مهر'],
  },
  'demo-restaurant': {
    customerNames: ['مهدی کاظمی', 'شرکت پردازش نوین', 'زهرا باقری'],
    secondCustomerCompany: 'شرکت پردازش نوین',
    customerCities: ['تهران', 'تهران', 'کرج'],
    productNames: ['خورشت قیمه (پرسی)', 'برنج ایرانی درجه یک'],
    productSkus: ['RS-301', 'RS-402'],
    productPrices: [1850000, 420000],
    productStocks: [35, 120],
    leadTitle: 'سفارش پذیرایی مراسم شرکتی',
    renewalTitle: 'تمدید قرارداد ناهار سازمانی',
    paidInvoiceDescription: 'خورشت قیمه (پرسی)',
    overdueInvoiceDescription: 'برنج ایرانی درجه یک — عمده',
    taskTitles: ['بررسی موجودی مواد اولیه آشپزخانه', 'پیگیری تسویه شرکت پردازش نوین'],
  },
  'demo-cafe': {
    customerNames: ['سارا امینی', 'دفتر خلاقیت آوا', 'امیرحسین نوری'],
    secondCustomerCompany: 'دفتر خلاقیت آوا',
    customerCities: ['تهران', 'تهران', 'اصفهان'],
    productNames: ['لاته دبل', 'شیرینی روز (عدد)'],
    productSkus: ['CF-501', 'CF-602'],
    productPrices: [285000, 165000],
    productStocks: [200, 48],
    leadTitle: 'سفارش قهوه و شیرینی جلسه تیم',
    renewalTitle: 'تمدید سفارش هفتگی دفتر',
    paidInvoiceDescription: 'لاته دبل',
    overdueInvoiceDescription: 'شیرینی روز — عمده',
    taskTitles: ['سفارش دانه قهوه و شیر', 'پیگیری تسویه دفتر خلاقیت آوا'],
  },
  'demo-bakery': {
    customerNames: ['فاطمه رضایی', 'کافه نان', 'حسین مرادی'],
    secondCustomerCompany: 'کافه نان',
    customerCities: ['تهران', 'تهران', 'شیراز'],
    productNames: ['نان سنگک تازه', 'کیک یزدی (عدد)'],
    productSkus: ['BK-701', 'BK-802'],
    productPrices: [85000, 320000],
    productStocks: [60, 24],
    leadTitle: 'سفارش نان و شیرینی مراسم تولد',
    renewalTitle: 'تمدید تامین صبحگاهی کافه',
    paidInvoiceDescription: 'نان سنگک تازه',
    overdueInvoiceDescription: 'کیک یزدی — عمده',
    taskTitles: ['برنامه‌ریزی پخت صبح فردا', 'پیگیری بدهی کافه نان'],
  },
  'demo-mobile-shop': {
    customerNames: ['پویا جعفری', 'فروشگاه دیجی‌پلاس', 'مریم صادقی'],
    secondCustomerCompany: 'فروشگاه دیجی‌پلاس',
    customerCities: ['تهران', 'تهران', 'مشهد'],
    productNames: ['گوشی سامسونگ A55', 'قاب سیلیکونی'],
    productSkus: ['MB-901', 'MB-902'],
    productPrices: [28500000, 450000],
    productStocks: [12, 85],
    leadTitle: 'سفارش عمده گوشی میان‌رده',
    renewalTitle: 'تمدید نمایندگی فروش',
    paidInvoiceDescription: 'گوشی سامسونگ A55',
    overdueInvoiceDescription: 'قاب سیلیکونی — عمده',
    taskTitles: ['هماهنگی ورود محموله جدید', 'پیگیری تسویه دیجی‌پلاس'],
  },
  'demo-electronics-store': {
    customerNames: ['رضا طاهری', 'شرکت فناوران', 'نگار احمدی'],
    secondCustomerCompany: 'شرکت فناوران',
    customerCities: ['تهران', 'تهران', 'کرج'],
    productNames: ['تلویزیون ۵۵ اینچ', 'هدفون بلوتوثی'],
    productSkus: ['EL-1101', 'EL-1102'],
    productPrices: [42000000, 3200000],
    productStocks: [8, 32],
    leadTitle: 'تامین تجهیزات سالن کنفرانس',
    renewalTitle: 'تمدید قرارداد تامین سازمانی',
    paidInvoiceDescription: 'تلویزیون ۵۵ اینچ',
    overdueInvoiceDescription: 'هدفون بلوتوثی — عمده',
    taskTitles: ['بررسی گارانتی محصولات انبار', 'پیگیری تسویه شرکت فناوران'],
  },
  'demo-flower-shop': {
    customerNames: ['نرگس بیات', 'هتل پارسیان', 'الهام کریمی'],
    secondCustomerCompany: 'هتل پارسیان',
    customerCities: ['تهران', 'تهران', 'اصفهان'],
    productNames: ['دسته گل رز قرمز', 'گلدان ارکیده'],
    productSkus: ['FL-1201', 'FL-1202'],
    productPrices: [1850000, 4200000],
    productStocks: [15, 10],
    leadTitle: 'سفارش گل تزئین سالن عروسی',
    renewalTitle: 'تمدید تامین هفتگی لابی هتل',
    paidInvoiceDescription: 'دسته گل رز قرمز',
    overdueInvoiceDescription: 'گلدان ارکیده — عمده',
    taskTitles: ['سفارش گل تازه فردا صبح', 'پیگیری تسویه هتل پارسیان'],
  },
  'demo-pet-shop': {
    customerNames: ['سمیه شاکری', 'کلینیک دامپزشکی مهربان', 'علی رحمانی'],
    secondCustomerCompany: 'کلینیک دامپزشکی مهربان',
    customerCities: ['تهران', 'تهران', 'کرج'],
    productNames: ['غذای خشک سگ ۱۰ کیلویی', 'قلاده چرمی'],
    productSkus: ['PT-1301', 'PT-1302'],
    productPrices: [2450000, 580000],
    productStocks: [22, 45],
    leadTitle: 'سفارش عمده غذای حیوانات خانگی',
    renewalTitle: 'تمدید تامین ماهانه کلینیک',
    paidInvoiceDescription: 'غذای خشک سگ ۱۰ کیلویی',
    overdueInvoiceDescription: 'قلاده چرمی — عمده',
    taskTitles: ['بررسی تاریخ انقضای اقلام', 'پیگیری بدهی کلینیک مهربان'],
  },
  'demo-optician': {
    customerNames: ['حمید نادری', 'مدرسه سلامت بینایی', 'زهرا محسنی'],
    secondCustomerCompany: 'مدرسه سلامت بینایی',
    customerCities: ['تهران', 'تهران', 'قم'],
    productNames: ['عینک طبی فریم فلزی', 'لنز تماسی ماهانه'],
    productSkus: ['OP-1401', 'OP-1402'],
    productPrices: [4200000, 1850000],
    productStocks: [18, 60],
    leadTitle: 'سفارش عینک ایمنی کارگاه',
    renewalTitle: 'تمدید تامین لنز سازمانی',
    paidInvoiceDescription: 'عینک طبی فریم فلزی',
    overdueInvoiceDescription: 'لنز تماسی ماهانه — عمده',
    taskTitles: ['پیگیری سفارش فریم وارداتی', 'پیگیری تسویه مدرسه بینایی'],
  },
  'demo-stationery-store': {
    customerNames: ['ریحانه ساداتی', 'مدرسه آینده‌سازان', 'مجتبی رضایی'],
    secondCustomerCompany: 'مدرسه آینده‌سازان',
    customerCities: ['تهران', 'تهران', 'شهریار'],
    productNames: ['دفتر ۱۰۰ برگ', 'خودکار آبی (بسته ۱۲ عددی)'],
    productSkus: ['ST-1501', 'ST-1502'],
    productPrices: [185000, 420000],
    productStocks: [200, 85],
    leadTitle: 'تامین لوازم التحریر ترم جدید',
    renewalTitle: 'تمدید قرارداد تامین مدرسه',
    paidInvoiceDescription: 'دفتر ۱۰۰ برگ',
    overdueInvoiceDescription: 'خودکار آبی — عمده',
    taskTitles: ['سفارش کالاهای پرفروش', 'پیگیری تسویه مدرسه آینده‌سازان'],
  },
  'demo-bookstore': {
    customerNames: ['امیرحسین قاسمی', 'کتابخانه دانشگاه', 'مینا شفیعی'],
    secondCustomerCompany: 'کتابخانه دانشگاه',
    customerCities: ['تهران', 'تهران', 'قم'],
    productNames: ['رمان «شب یرگ»', 'کتاب درسی ریاضی دهم'],
    productSkus: ['BK-1601', 'BK-1602'],
    productPrices: [580000, 420000],
    productStocks: [35, 80],
    leadTitle: 'سفارش عمده کتاب\u200cهای پرفروش',
    renewalTitle: 'تمدید تامین کتابخانه',
    paidInvoiceDescription: 'رمان «شب یرگ»',
    overdueInvoiceDescription: 'کتاب درسی ریاضی دهم — عمده',
    taskTitles: ['پیگیری سفارش ناشر', 'پیگیری تسویه کتابخانه دانشگاه'],
  },
  'demo-hardware-store': {
    customerNames: ['بهزاد رحیمی', 'پیمانکاری سازه‌گستر', 'یاسر طهماسبی'],
    secondCustomerCompany: 'پیمانکاری سازه‌گستر',
    customerCities: ['تهران', 'تهران', 'کرج'],
    productNames: ['دریل برقی ۱۳ میل', 'پیچ و مهره ۶ میل (بسته)'],
    productSkus: ['HW-1701', 'HW-1702'],
    productPrices: [8500000, 320000],
    productStocks: [14, 200],
    leadTitle: 'تامین ابزار پروژه ساختمانی',
    renewalTitle: 'تمدید حساب اعتباری پیمانکار',
    paidInvoiceDescription: 'دریل برقی ۱۳ میل',
    overdueInvoiceDescription: 'پیچ و مهره ۶ میل — عمده',
    taskTitles: ['بررسی موجودی ابزار برقی', 'پیگیری بدهی سازه‌گستر'],
  },
  'demo-cosmetics-store': {
    customerNames: ['سحر صبوری', 'سالن زیبایی ماه‌چهره', 'نازنین فلاح'],
    secondCustomerCompany: 'سالن زیبایی ماه‌چهره',
    customerCities: ['تهران', 'تهران', 'تهران'],
    productNames: ['کرم مرطوب‌کننده صورت', 'رژ لب مات'],
    productSkus: ['CS-1801', 'CS-1802'],
    productPrices: [1850000, 980000],
    productStocks: [42, 65],
    leadTitle: 'سفارش عمده محصولات مراقبت پوست',
    renewalTitle: 'تمدید تامین سالن زیبایی',
    paidInvoiceDescription: 'کرم مرطوب‌کننده صورت',
    overdueInvoiceDescription: 'رژ لب — عمده',
    taskTitles: ['بررسی تاریخ انقضای لوازم آرایشی', 'پیگیری تسویه ماه‌چهره'],
  },
  'demo-jewelry-store': {
    customerNames: ['پریسا نادری', 'مزون نقش', 'لیلا فرهمند'],
    secondCustomerCompany: 'مزون نقش',
    customerCities: ['تهران', 'تهران', 'اصفهان'],
    productNames: ['انگشتر طلا ۱۸ عیار', 'گردنبند نقره'],
    productSkus: ['JW-1901', 'JW-1902'],
    productPrices: [28500000, 8500000],
    productStocks: [6, 12],
    leadTitle: 'سفارش ست طلا برای مراسم',
    renewalTitle: 'تمدید همکاری مزون',
    paidInvoiceDescription: 'انگشتر طلا ۱۸ عیار',
    overdueInvoiceDescription: 'گردنبند نقره — عمده',
    taskTitles: ['هماهنگی سفارش طلاسازی', 'پیگیری تسویه مزون نقش'],
  },
};

export const CLINIC_PRESETS: Record<string, ClinicSeedPreset> = {
  'demo-clinic': {
    patientNames: ['دکتر آرش میرزایی', 'فاطمه حیدری', 'محمد جوادی'],
    patientCities: ['تهران', 'کرج', 'تهران'],
    patientNote: 'ایمپلنت — دو جلسه باقی\u200cمانده',
    serviceNames: ['معاینه و مشاوره', 'جرم\u200cگیری و بروساژ', 'ایمپلنت دندان'],
    servicePrices: [850000, 1200000, 45000000],
    leadTitle: 'درخواست مشاوره ارتودنسی',
    wonLeadTitle: 'طرح درمان ایمپلنت',
    reminderTitle: 'یادآوری نوبت فاطمه حیدری',
    reminderMessage: 'جلسه دوم ایمپلنت',
  },
  'demo-medical-office': {
    patientNames: ['حمید نادری', 'نرگس محسنی', 'رضا سلیمانی'],
    patientCities: ['تهران', 'تهران', 'اسلامشهر'],
    patientNote: 'چکاپ دوره\u200cای و پیگیری فشار خون',
    serviceNames: ['ویزیت پزشک عمومی', 'آزمایش چکاپ', 'تفسیر نتایج و نسخه'],
    servicePrices: [650000, 1800000, 950000],
    leadTitle: 'درخواست ویزیت خانواده',
    wonLeadTitle: 'پکیج چکاپ سالانه',
    reminderTitle: 'یادآوری چکاپ نرگس محسنی',
    reminderMessage: 'پیگیری نتایج آزمایش و مراجعه مجدد',
  },
  'demo-hospital': {
    patientNames: ['بهزاد رحیمی', 'مینا شفیعی', 'یاسر طهماسبی'],
    patientCities: ['تهران', 'قم', 'کرج'],
    patientNote: 'نیازمند پیگیری ترخیص و کنترل هزینه خدمات',
    serviceNames: ['پذیرش تخصصی', 'رادیولوژی و تصویربرداری', 'خدمات بستری روزانه'],
    servicePrices: [1500000, 4200000, 18000000],
    leadTitle: 'درخواست جراحی سرپایی',
    wonLeadTitle: 'پذیرش خدمات بستری',
    reminderTitle: 'یادآوری پیگیری پرونده مینا شفیعی',
    reminderMessage: 'هماهنگی ترخیص و تسویه نهایی',
  },
  'demo-treatment-center': {
    patientNames: ['امیرحسین قاسمی', 'زهرا کیانی', 'احسان مرادی'],
    patientCities: ['کرج', 'فردیس', 'کرج'],
    patientNote: 'درمانگاه شبانه\u200cروزی — مراجعه مجدد ۴۸ ساعته',
    serviceNames: ['ویزیت عمومی', 'تزریقات و پانسمان', 'آزمایش فوری'],
    servicePrices: [550000, 780000, 1250000],
    leadTitle: 'درخواست خدمات فوری خانوادگی',
    wonLeadTitle: 'پرونده درمان سرپایی',
    reminderTitle: 'یادآوری مراجعه زهرا کیانی',
    reminderMessage: 'کنترل وضعیت و تمدید نسخه',
  },
  'demo-veterinary-clinic': {
    patientNames: ['سگ «رکس» — صاحب: علی موسوی', 'گربه «پشی» — صاحب: سارا امینی', 'سگ «ماکس» — صاحب: رضا کریمی'],
    patientCities: ['تهران', 'تهران', 'کرج'],
    patientNote: 'واکسن سالانه — نوبت بعدی ۱۲ ماه',
    serviceNames: ['معاینه عمومی', 'واکسن هاری و هپاتیت', 'جراحی کوچک'],
    servicePrices: [450000, 850000, 8500000],
    leadTitle: 'درخواست واکسن گله سگ‌های نگهبانی',
    wonLeadTitle: 'پرونده درمان سگ «پشی»',
    reminderTitle: 'یادآوری واکسن «رکس»',
    reminderMessage: 'تزریق واکسن سالانه',
  },
};

export const GENERAL_PRESETS: Record<string, GeneralSeedPreset> = {
  'demo-contracting': {
    firstCustomerName: 'شرکت توسعه عمران آریا',
    firstCustomerCompany: 'توسعه عمران آریا',
    secondCustomerName: 'مجتبی رضایی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'پرند',
    leadTitles: ['مذاکره پیمان فاز دوم پروژه', 'ارسال صورت\u200cوضعیت پروژه عمرانی'],
    invoiceDescription: 'صورت\u200cوضعیت اجرای فاز اول',
    taskTitles: ['پیگیری تایید صورت\u200cوضعیت', 'هماهنگی برنامه هفتگی کارگاه'],
    invoiceAmount: 125000000,
    paidAmount: 45000000,
  },
  'demo-education-center': {
    firstCustomerName: 'آموزش و پژوهش پارس',
    firstCustomerCompany: 'آموزش و پژوهش پارس',
    secondCustomerName: 'ریحانه ساداتی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'شهریار',
    leadTitles: ['ثبت\u200cنام دوره سازمانی', 'ارسال پیش\u200cفاکتور شهریه ترم جدید'],
    invoiceDescription: 'شهریه دوره مهارت\u200cافزایی',
    taskTitles: ['پیگیری واریز شهریه سازمانی', 'به\u200cروزرسانی برنامه کلاس\u200cها'],
    invoiceAmount: 68000000,
    paidAmount: 25000000,
  },
  'demo-beauty-salon': {
    firstCustomerName: 'نرگس بیات',
    firstCustomerCompany: 'باشگاه مشتریان ماه\u200cچهره',
    secondCustomerName: 'سحر صبوری',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'تهران',
    leadTitles: ['رزرو پکیج خدمات عروس', 'ارسال پیش\u200cفاکتور خدمات VIP'],
    invoiceDescription: 'پکیج خدمات زیبایی VIP',
    taskTitles: ['پیگیری رزرو خدمات هفته آینده', 'هماهنگی شیفت تیم خدمات'],
    invoiceAmount: 54000000,
    paidAmount: 18000000,
  },
  'demo-real-estate': {
    firstCustomerName: 'خانواده رستمی',
    firstCustomerCompany: 'خانواده رستمی',
    secondCustomerName: 'مهسا کریمی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'کرج',
    leadTitles: ['بازدید آپارتمان ۱۲۰ متری سعادت\u200cآباد', 'ارسال پیش\u200cفاکتور خدمات مشاوره خرید'],
    invoiceDescription: 'حق مشاوره و کارمزد فروش ملک',
    taskTitles: ['هماهنگی بازدید ملک جدید', 'پیگیری مدارک انتقال سند'],
    invoiceAmount: 85000000,
    paidAmount: 25000000,
  },
  'demo-law-office': {
    firstCustomerName: 'شرکت فناوران صنعت',
    firstCustomerCompany: 'فناوران صنعت',
    secondCustomerName: 'حامد قاسمی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'اصفهان',
    leadTitles: ['مشاوره پرونده قرارداد تجاری', 'ارسال پیش\u200cفاکتور حق\u200cالوکاله'],
    invoiceDescription: 'حق\u200cالوکاله و هزینه تنظیم لایحه',
    taskTitles: ['پیگیری جلسه دادگاه هفته آینده', 'تهیه مستندات تکمیلی پرونده'],
    invoiceAmount: 45000000,
    paidAmount: 15000000,
  },
  'demo-accounting-office': {
    firstCustomerName: 'تولیدی پارس پلاست',
    firstCustomerCompany: 'تولیدی پارس پلاست',
    secondCustomerName: 'الناز صمدی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'شهریار',
    leadTitles: ['قرارداد حسابداری ماهانه', 'ارسال پیش\u200cفاکتور اظهارنامه'],
    invoiceDescription: 'حق\u200cالزحمه حسابداری فصل اول',
    taskTitles: ['پیگیری مدارک مالی مشتری', 'ارسال گزارش مالی ماهانه'],
    invoiceAmount: 28000000,
    paidAmount: 12000000,
  },
  'demo-gym': {
    firstCustomerName: 'باشگاه مشتریان انرژی+',
    firstCustomerCompany: 'باشگاه انرژی+',
    secondCustomerName: 'امیرحسین نوری',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'تهران',
    leadTitles: ['ثبت\u200cنام عضویت سالانه', 'ارسال پیش\u200cفاکتور پکیج خانوادگی'],
    invoiceDescription: 'حق عضویت ۶ ماهه + مربی خصوصی',
    taskTitles: ['پیگیری تمدید عضویت', 'هماهنگی برنامه تمرین جدید'],
    invoiceAmount: 18500000,
    paidAmount: 8500000,
  },
  'demo-auto-repair': {
    firstCustomerName: 'شرکت حمل‌ونقل باران',
    firstCustomerCompany: 'حمل\u200cونقل باران',
    secondCustomerName: 'رضا سلیمانی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'اسلامشهر',
    leadTitles: ['سرویس دوره\u200cای ناوگان', 'ارسال پیش\u200cفاکتور تعمیر موتور'],
    invoiceDescription: 'تعمیر گیربکس و تعویض روغن',
    taskTitles: ['پیگیری قطعات سفارش\u200cداده', 'هماهنگی تحویل خودرو'],
    invoiceAmount: 32000000,
    paidAmount: 12000000,
  },
  'demo-tailor-shop': {
    firstCustomerName: 'مزون نقش',
    firstCustomerCompany: 'مزون نقش',
    secondCustomerName: 'فاطمه حیدری',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'کرج',
    leadTitles: ['سفارش دوخت کت و شلوار', 'ارسال پیش\u200cفاکتور لباس عروس'],
    invoiceDescription: 'دوخت کت و شلوار سفارشی',
    taskTitles: ['پیگیری اندازه\u200cگیری مشتری', 'هماهنگی تحویل لباس'],
    invoiceAmount: 12500000,
    paidAmount: 5000000,
  },
  'demo-cleaning-services': {
    firstCustomerName: 'مجتمع اداری آسمان',
    firstCustomerCompany: 'مجتمع اداری آسمان',
    secondCustomerName: 'زهرا کیانی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'کرج',
    leadTitles: ['قرارداد نظافت ماهانه ساختمان', 'ارسال پیش\u200cفاکتور نظافت عمیق'],
    invoiceDescription: 'خدمات نظافت ماهانه طبقات اداری',
    taskTitles: ['برنامه\u200cریزی شیفت هفتگی', 'پیگیری تسویه مجتمع آسمان'],
    invoiceAmount: 42000000,
    paidAmount: 18000000,
  },
  'demo-marketing-agency': {
    firstCustomerName: 'استارتاپ نوآوران',
    firstCustomerCompany: 'نوآوران',
    secondCustomerName: 'نگین صالحی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'تهران',
    leadTitles: ['پیشنهاد کمپین اینستاگرام', 'ارسال پیش\u200cفاکتور تولید محتوا'],
    invoiceDescription: 'حق\u200cالزحمه مدیریت شبکه\u200cهای اجتماعی (ماهانه)',
    taskTitles: ['ارسال گزارش عملکرد کمپین', 'هماهنگی جلسه استراتژی محتوا'],
    invoiceAmount: 35000000,
    paidAmount: 15000000,
  },
  'demo-printing-shop': {
    firstCustomerName: 'نمایشگاه کتاب تهران',
    firstCustomerCompany: 'نمایشگاه کتاب',
    secondCustomerName: 'مجتبی رضایی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'پرند',
    leadTitles: ['سفارش چاپ بروشور نمایشگاه', 'ارسال پیش\u200cفاکتور چاپ کاتالوگ'],
    invoiceDescription: 'چاپ بروشور A4 — ۵۰۰۰ نسخه',
    taskTitles: ['پیگیری تایید طراحی', 'هماهنگی تحویل چاپ'],
    invoiceAmount: 18500000,
    paidAmount: 8500000,
  },
  'demo-insurance-agency': {
    firstCustomerName: 'شرکت توسعه عمران آریا',
    firstCustomerCompany: 'توسعه عمران آریا',
    secondCustomerName: 'حمید نادری',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'تهران',
    leadTitles: ['بیمه آتش\u200cسوزی ساختمان', 'ارسال پیش\u200cفاکتور بیمه شخص ثالث'],
    invoiceDescription: 'حق بیمه سالانه بیمه آتش\u200cسوزی',
    taskTitles: ['پیگیری صدور بیمه\u200cنامه', 'یادآوری تمدید بیمه مشتری'],
    invoiceAmount: 45000000,
    paidAmount: 45000000,
  },
  'demo-appliance-repair': {
    firstCustomerName: 'هتل پارسیان',
    firstCustomerCompany: 'هتل پارسیان',
    secondCustomerName: 'سمیه شاکری',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'ورامین',
    leadTitles: ['قرارداد سرویس یخچال و ماشین لباسشویی', 'ارسال پیش\u200cفاکتور تعمیر کولر'],
    invoiceDescription: 'تعمیر یخچال فریزر — تعویض کمپرسور',
    taskTitles: ['هماهنگی اعزام تکنسین', 'پیگیری قطعه یدکی'],
    invoiceAmount: 8500000,
    paidAmount: 3500000,
  },
  'demo-photography-studio': {
    firstCustomerName: 'خانواده رستمی',
    firstCustomerCompany: 'خانواده رستمی',
    secondCustomerName: 'پریسا نادری',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'اصفهان',
    leadTitles: ['رزرو عکاسی عروسی', 'ارسال پیش\u200cفاکتور آلبوم دیجیتال'],
    invoiceDescription: 'پکیج عکاسی مراسم — ۸ ساعت',
    taskTitles: ['هماهنگی زمانبندی عکاسی', 'پیگیری ویرایش و تحویل آلبوم'],
    invoiceAmount: 45000000,
    paidAmount: 20000000,
  },
  'demo-daycare-center': {
    firstCustomerName: 'خانواده اکبری',
    firstCustomerCompany: 'خانواده اکبری',
    secondCustomerName: 'مریم صادقی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'مشهد',
    leadTitles: ['ثبت\u200cنام کودک ۳ ساله', 'ارسال پیش\u200cفاکتور شهریه ترم'],
    invoiceDescription: 'شهریه ماهانه مهدکودک',
    taskTitles: ['پیگیری تکمیل پرونده پزشکی', 'هماهنگی جلسه والدین'],
    invoiceAmount: 8500000,
    paidAmount: 8500000,
  },
  'demo-computer-service': {
    firstCustomerName: 'شرکت فناوران',
    firstCustomerCompany: 'فناوران',
    secondCustomerName: 'پویا جعفری',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'مشهد',
    leadTitles: ['قرارداد پشتیبانی IT سازمانی', 'ارسال پیش\u200cفاکتور تعمیر سرور'],
    invoiceDescription: 'حق\u200cالزحمه پشتیبانی شبکه (ماهانه)',
    taskTitles: ['پیگیری تعمیر لپ\u200cتاپ مشتری', 'بروزرسانی نرم\u200cافزارهای امنیتی'],
    invoiceAmount: 28000000,
    paidAmount: 12000000,
  },
  'demo-restaurant': {
    firstCustomerName: 'شرکت پردازش نوین',
    firstCustomerCompany: 'شرکت پردازش نوین',
    secondCustomerName: 'مهدی کاظمی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'کرج',
    leadTitles: ['سفارش پذیرایی مراسم شرکتی', 'تمدید قرارداد ناهار سازمانی'],
    invoiceDescription: 'خورشت قیمه (پرسی) — پذیرایی سازمانی',
    taskTitles: ['بررسی موجودی مواد اولیه آشپزخانه', 'پیگیری تسویه شرکت پردازش نوین'],
    invoiceAmount: 45000000,
    paidAmount: 18000000,
  },
  'demo-cafe': {
    firstCustomerName: 'دفتر خلاقیت آوا',
    firstCustomerCompany: 'دفتر خلاقیت آوا',
    secondCustomerName: 'سارا امینی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'اصفهان',
    leadTitles: ['سفارش قهوه و شیرینی جلسه تیم', 'تمدید سفارش هفتگی دفتر'],
    invoiceDescription: 'لاته دبل — سفارش جلسه',
    taskTitles: ['سفارش دانه قهوه و شیر', 'پیگیری تسویه دفتر خلاقیت آوا'],
    invoiceAmount: 8500000,
    paidAmount: 3500000,
  },
  'demo-bakery': {
    firstCustomerName: 'کافه نان',
    firstCustomerCompany: 'کافه نان',
    secondCustomerName: 'فاطمه رضایی',
    firstCustomerCity: 'تهران',
    secondCustomerCity: 'شیراز',
    leadTitles: ['سفارش نان و شیرینی مراسم تولد', 'تمدید تامین صبحگاهی کافه'],
    invoiceDescription: 'نان سنگک تازه — تامین روزانه',
    taskTitles: ['برنامه\u200cریزی پخت صبح فردا', 'پیگیری بدهی کافه نان'],
    invoiceAmount: 12000000,
    paidAmount: 5000000,
  },
};

export type ClinicPackExtensionPreset = {
  practitionerName: string;
  specialty: string;
  filePrefix: string;
  patientNotes: [string, string, string];
  allergies?: string;
  appointmentReasons: {
    today: string;
    afternoon: string;
    upcoming: string;
    noShow: string;
  };
  visit: {
    chiefComplaint: string;
    treatmentNotes: string;
  };
  taskTitle: string;
  followUpOnCompletedAppt?: boolean;
};

export const CLINIC_PACK_EXTENSIONS: Record<string, ClinicPackExtensionPreset> = {
  'demo-clinic': {
    practitionerName: 'دکتر نیلوفر رضایی',
    specialty: 'دندانپزشک',
    filePrefix: 'P',
    patientNotes: ['مراجع دوره\u200cای', 'ایمپلنت — دو جلسه باقی\u200cمانده', ''],
    allergies: 'پنی\u200cسیلین',
    appointmentReasons: {
      today: 'جلسه دوم ایمپلنت',
      afternoon: 'جرم\u200cگیری',
      upcoming: 'معاینه دوره\u200cای',
      noShow: 'پیگیری درمان',
    },
    visit: {
      chiefComplaint: 'ایمپلنت فک پایین',
      treatmentNotes: 'پیچ گذاری انجام شد — جلسه بعدی پروتز',
    },
    taskTitle: 'تماس یادآوری نوبت فاطمه حیدری',
    followUpOnCompletedAppt: true,
  },
  'demo-medical-office': {
    practitionerName: 'دکتر حسین نادری',
    specialty: 'پزشک عمومی',
    filePrefix: 'P',
    patientNotes: ['چکاپ سالانه', 'فشار خون — نیاز به پیگیری', ''],
    allergies: 'آسپرین',
    appointmentReasons: {
      today: 'پیگیری فشار خون',
      afternoon: 'تزریق واکسن',
      upcoming: 'چکاپ دوره\u200cای',
      noShow: 'تمدید نسخه',
    },
    visit: {
      chiefComplaint: 'سردرد و خستگی',
      treatmentNotes: 'فشار ۱۳/۸ — نسخه تجویز شد — کنترل ۲ هفته',
    },
    taskTitle: 'تماس یادآوری چکاپ نرگس محسنی',
    followUpOnCompletedAppt: true,
  },
  'demo-hospital': {
    practitionerName: 'دکتر مریم شفیعی',
    specialty: 'متخصص داخلی',
    filePrefix: 'H',
    patientNotes: ['پذیرش سرپایی', 'بستری — پیگیری ترخیص', ''],
    appointmentReasons: {
      today: 'هماهنگی ترخیص',
      afternoon: 'تصویربرداری MRI',
      upcoming: 'ویزیت پس از ترخیص',
      noShow: 'پیگیری نتایج آزمایش',
    },
    visit: {
      chiefComplaint: 'درد شکم و تهوع',
      treatmentNotes: 'سونوگرافی انجام شد — در انتظار نتیجه',
    },
    taskTitle: 'پیگیری پرونده بستری مینا شفیعی',
    followUpOnCompletedAppt: true,
  },
  'demo-treatment-center': {
    practitionerName: 'دکتر علی مرادی',
    specialty: 'پزشک عمومی',
    filePrefix: 'T',
    patientNotes: ['مراجع فوری', 'تزریقات — مراجعه مجدد ۴۸ ساعت', ''],
    allergies: 'سولفا',
    appointmentReasons: {
      today: 'تزریق و پانسمان',
      afternoon: 'آزمایش فوری',
      upcoming: 'کنترل وضعیت',
      noShow: 'تمدید نسخه',
    },
    visit: {
      chiefComplaint: 'تب و گلودرد',
      treatmentNotes: 'آزمایش CRP — آنتی\u200cبیوتیک تجویز شد',
    },
    taskTitle: 'تماس یادآوری مراجعه زهرا کیانی',
    followUpOnCompletedAppt: true,
  },
  'demo-veterinary-clinic': {
    practitionerName: 'دکتر سارا مهربان',
    specialty: 'دامپزشک',
    filePrefix: 'V',
    patientNotes: ['واکسن سالانه', 'عفونت گوش — درمان ۵ روزه', ''],
    allergies: 'پنی\u200cسیلین (حساسیت دارویی)',
    appointmentReasons: {
      today: 'تزریق واکسن سالانه',
      afternoon: 'معاینه عفونت گوش',
      upcoming: 'کنترل پس از درمان',
      noShow: 'پیگیری واکسن',
    },
    visit: {
      chiefComplaint: 'بی\u200cحالی و کم\u200cاشتهایی',
      treatmentNotes: 'معاینه انجام شد — نسخه غذایی و مکمل تجویز شد',
    },
    taskTitle: 'تماس یادآوری واکسن «رکس»',
    followUpOnCompletedAppt: true,
  },
};

export type RetailPackExtensionPreset = {
  reorderLevels: [number, number];
  stockInReason: string;
  stockOutReason: string;
  stockBulkReason: string;
  bulkRef?: string;
};

export const RETAIL_PACK_EXTENSIONS: Record<string, RetailPackExtensionPreset> = {
  'demo-retail': {
    reorderLevels: [50, 100],
    stockInReason: 'خرید فصل پاییز',
    stockOutReason: 'فروش خرده',
    stockBulkReason: 'فروش عمده بوتیک ماهان',
    bulkRef: 'SL-8891',
  },
  'demo-supermarket': {
    reorderLevels: [30, 80],
    stockInReason: 'دریافت محموله توزیع',
    stockOutReason: 'فروش روزانه',
    stockBulkReason: 'تامین رستوران گیلاس',
    bulkRef: 'SM-4401',
  },
  'demo-pharmacy': {
    reorderLevels: [100, 50],
    stockInReason: 'دریافت از شرکت پخش',
    stockOutReason: 'فروش نسخه\u200cای',
    stockBulkReason: 'تامین درمانگاه مهر',
    bulkRef: 'PH-3301',
  },
  'demo-restaurant': {
    reorderLevels: [40, 100],
    stockInReason: 'خرید مواد اولیه',
    stockOutReason: 'مصرف آشپزخانه روزانه',
    stockBulkReason: 'فروش روزانه میز و پذیرایی',
    bulkRef: 'RS-2201',
  },
  'demo-cafe': {
    reorderLevels: [150, 40],
    stockInReason: 'دریافت دانه قهوه و شیر',
    stockOutReason: 'فروش روزانه نوشیدنی',
    stockBulkReason: 'سفارش دفتر خلاقیت آوا',
    bulkRef: 'CF-5501',
  },
  'demo-bakery': {
    reorderLevels: [50, 20],
    stockInReason: 'خرید آرد و مواد پخت',
    stockOutReason: 'فروش صبحگاهی',
    stockBulkReason: 'تامین کافه نان',
    bulkRef: 'BK-7701',
  },
  'demo-mobile-shop': {
    reorderLevels: [10, 60],
    stockInReason: 'ورود محموله گوشی',
    stockOutReason: 'فروش خرده',
    stockBulkReason: 'فروش عمده دیجی\u200cپلاس',
    bulkRef: 'MB-9901',
  },
  'demo-electronics-store': {
    reorderLevels: [5, 25],
    stockInReason: 'دریافت از نمایندگی',
    stockOutReason: 'فروش خرده',
    stockBulkReason: 'تامین شرکت فناوران',
    bulkRef: 'EL-11001',
  },
  'demo-flower-shop': {
    reorderLevels: [10, 8],
    stockInReason: 'خرید گل تازه بازار',
    stockOutReason: 'فروش دسته\u200cگل',
    stockBulkReason: 'تزئین لابی هتل پارسیان',
    bulkRef: 'FL-12001',
  },
  'demo-pet-shop': {
    reorderLevels: [25, 40],
    stockInReason: 'دریافت غذای حیوانات',
    stockOutReason: 'فروش خرده',
    stockBulkReason: 'تامین کلینیک مهربان',
    bulkRef: 'PT-13001',
  },
  'demo-optician': {
    reorderLevels: [15, 50],
    stockInReason: 'دریافت فریم و لنز',
    stockOutReason: 'فروش عینک',
    stockBulkReason: 'تامین مدرسه بینایی',
    bulkRef: 'OP-14001',
  },
  'demo-stationery-store': {
    reorderLevels: [150, 80],
    stockInReason: 'خرید فصل مدرسه',
    stockOutReason: 'فروش خرده',
    stockBulkReason: 'تامین مدرسه آینده\u200cسازان',
    bulkRef: 'ST-15001',
  },
  'demo-bookstore': {
    reorderLevels: [30, 60],
    stockInReason: 'دریافت از ناشر',
    stockOutReason: 'فروش خرده',
    stockBulkReason: 'تامین کتابخانه دانشگاه',
    bulkRef: 'BK-16001',
  },
  'demo-hardware-store': {
    reorderLevels: [10, 150],
    stockInReason: 'خرید عمده ابزار',
    stockOutReason: 'فروش خرده',
    stockBulkReason: 'تامین پروژه سازه\u200cگستر',
    bulkRef: 'HW-17001',
  },
  'demo-cosmetics-store': {
    reorderLevels: [40, 55],
    stockInReason: 'دریافت محصولات آرایشی',
    stockOutReason: 'فروش خرده',
    stockBulkReason: 'تامین سالن ماه\u200cچهره',
    bulkRef: 'CS-18001',
  },
  'demo-jewelry-store': {
    reorderLevels: [5, 10],
    stockInReason: 'دریافت از طلاسازی',
    stockOutReason: 'فروش خرده',
    stockBulkReason: 'سفارش مزون نقش',
    bulkRef: 'JW-19001',
  },
};
