import type { DemoScenario, DemoScenarioId } from './types';
import { listSpecialties } from '../packs/specialties';

const BASE_DEMO_SCENARIOS: Record<string, DemoScenario> = {
  general: {
    id: 'general',
    orgSlug: 'demo-general',
    title: 'خدمات B2B — هسته مشترک',
    subtitle: 'شرکت خدمات تدبیر کسب‌وکار',
    industryPack: 'GENERAL',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر عامل خدمات سازمانی',
    valueProposition:
      'مدیریت یکپارچه مشتری، لید، فاکتور و پیگیری — بدون پراکندگی ابزار',
    highlights: [
      'مطالبات سررسید گذشته در یک نگاه',
      'لیدهای نیازمند پیگیری',
      'دستیار عملیاتی برای اولویت‌های امروز',
    ],
    salesWalkthroughOrder: 1,
    investorWalkthroughOrder: 1,
    firstStopHref: '/dashboard',
    showcaseLinks: [
      { label: 'داشبورد', href: '/dashboard', description: 'سیگنال‌های عملیاتی روز' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
      { label: 'گزارش‌ها', href: '/reports' },
      { label: 'دستیار', href: '/conversation' },
    ],
  },
  clinic: {
    id: 'clinic',
    orgSlug: 'demo-clinic',
    title: 'کلینیک دندانپزشکی',
    subtitle: 'کلینیک دندانپزشکی سپهر',
    industryPack: 'CLINIC',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای (آزمایشی)',
    personaTitle: 'پزشک / مدیر کلینیک',
    valueProposition: 'نوبت‌دهی، بیماران و پیگیری درمان روی همان هسته مالی',
    highlights: [
      'نوبت‌های امروز و از دست رفته',
      'پرونده بیمار متصل به مشتری',
      'یادآوری پیگیری درمان',
    ],
    salesWalkthroughOrder: 2,
    investorWalkthroughOrder: 3,
    firstStopHref: '/clinic',
    showcaseLinks: [
      { label: 'کلینیک', href: '/clinic' },
      { label: 'نوبت‌ها', href: '/clinic/appointments' },
      { label: 'بیماران', href: '/clinic/patients' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  travel: {
    id: 'travel',
    orgSlug: 'demo-travel',
    title: 'آژانس مسافرتی',
    subtitle: 'آژانس مسافرتی آسمان آبی',
    industryPack: 'TRAVEL_AGENCY',
    planCode: 'FREE',
    planLabel: 'رایگان — نمایش ارتقا',
    personaTitle: 'مشاور مسافرتی',
    valueProposition: 'رزرو، اعزام و مانده حساب در یک جریان کاری',
    highlights: [
      'درخواست‌های باز و اعزام پیشِ رو',
      'نمونه قفل بسته عمودی در طرح رایگان',
      'مسیر ارتقا به استارتر/حرفه‌ای',
    ],
    salesWalkthroughOrder: 3,
    investorWalkthroughOrder: 4,
    firstStopHref: '/travel',
    showcaseLinks: [
      { label: 'مسافرتی', href: '/travel' },
      { label: 'رزروها', href: '/travel/bookings' },
      { label: 'طرح‌ها', href: '/pricing' },
      { label: 'اشتراک', href: '/settings/billing' },
    ],
  },
  retail: {
    id: 'retail',
    orgSlug: 'demo-retail',
    title: 'خرده‌فروشی پوشاک',
    subtitle: 'فروشگاه پوشاک آرتین',
    industryPack: 'RETAIL',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر عملیات فروشگاه',
    valueProposition: 'موجودی، کمبود کالا و فروش در یک پنل',
    highlights: [
      'هشدار کم‌موجودی',
      'گردش انبار',
      'فاکتور و مطالبات متصل',
    ],
    salesWalkthroughOrder: 4,
    investorWalkthroughOrder: 2,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'فروشگاه', href: '/retail' },
      { label: 'محصولات', href: '/retail/products' },
      { label: 'موجودی', href: '/retail/inventory' },
      { label: 'داشبورد', href: '/dashboard' },
    ],
  },
  'medical-office': {
    id: 'medical-office',
    orgSlug: 'demo-medical-office',
    title: 'مطب پزشک عمومی',
    subtitle: 'مطب دکتر نادری',
    industryPack: 'CLINIC',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'پزشک / منشی مطب',
    valueProposition: 'مدیریت نوبت، بیمار و صورتحساب برای مطب‌های کوچک',
    highlights: ['تقویم نوبت روزانه', 'پرونده بیمار', 'پیگیری مراجعات دوره‌ای'],
    salesWalkthroughOrder: 5,
    investorWalkthroughOrder: 5,
    firstStopHref: '/clinic',
    showcaseLinks: [
      { label: 'داشبورد کلینیک', href: '/clinic' },
      { label: 'نوبت‌ها', href: '/clinic/appointments' },
      { label: 'بیماران', href: '/clinic/patients' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  hospital: {
    id: 'hospital',
    orgSlug: 'demo-hospital',
    title: 'بیمارستان خصوصی',
    subtitle: 'بیمارستان مهر سلامت',
    industryPack: 'CLINIC',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر خدمات درمانی',
    valueProposition: 'جریان نوبت، پرونده و خدمات مالی در مقیاس بزرگ‌تر',
    highlights: ['مدیریت حجم بالای مراجعان', 'مسیر درمان تا تسویه', 'گزارش عملیاتی'],
    salesWalkthroughOrder: 6,
    investorWalkthroughOrder: 6,
    firstStopHref: '/clinic',
    showcaseLinks: [
      { label: 'داشبورد کلینیک', href: '/clinic' },
      { label: 'نوبت‌ها', href: '/clinic/appointments' },
      { label: 'بیماران', href: '/clinic/patients' },
      { label: 'گزارش‌ها', href: '/reports' },
    ],
  },
  'treatment-center': {
    id: 'treatment-center',
    orgSlug: 'demo-treatment-center',
    title: 'درمانگاه شبانه‌روزی',
    subtitle: 'درمانگاه امید',
    industryPack: 'CLINIC',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر درمانگاه',
    valueProposition: 'ثبت سریع نوبت و خدمات با تمرکز بر عملیات شیفتی',
    highlights: ['نوبت‌های اورژانسی', 'نمای سریع پرونده', 'پیگیری مراجعات'],
    salesWalkthroughOrder: 7,
    investorWalkthroughOrder: 9,
    firstStopHref: '/clinic',
    showcaseLinks: [
      { label: 'داشبورد کلینیک', href: '/clinic' },
      { label: 'نوبت‌ها', href: '/clinic/appointments' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'وظایف', href: '/tasks' },
    ],
  },
  supermarket: {
    id: 'supermarket',
    orgSlug: 'demo-supermarket',
    title: 'سوپرمارکت محلی',
    subtitle: 'سوپرمارکت باران',
    industryPack: 'RETAIL',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر فروشگاه',
    valueProposition: 'مدیریت موجودی سریع‌گردش و سفارش‌گذاری مجدد',
    highlights: ['هشدار کم‌موجودی', 'ورود/خروج کالا', 'فاکتور روزانه'],
    salesWalkthroughOrder: 8,
    investorWalkthroughOrder: 7,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'محصولات', href: '/retail/products' },
      { label: 'موجودی', href: '/retail/inventory' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  pharmacy: {
    id: 'pharmacy',
    orgSlug: 'demo-pharmacy',
    title: 'داروخانه',
    subtitle: 'داروخانه درمان‌یار',
    industryPack: 'RETAIL',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر داروخانه',
    valueProposition: 'کنترل موجودی اقلام حساس و مدیریت فروش روزانه',
    highlights: ['اقلام رو‌به‌اتمام', 'تراکنش‌های روز', 'پیگیری بدهی مشتریان'],
    salesWalkthroughOrder: 9,
    investorWalkthroughOrder: 8,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'موجودی', href: '/retail/inventory' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'گزارش‌ها', href: '/reports' },
    ],
  },
  contracting: {
    id: 'contracting',
    orgSlug: 'demo-contracting',
    title: 'شرکت پیمانکاری',
    subtitle: 'پیمانکاری سازه‌گستر',
    industryPack: 'CONTRACTING',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر پروژه / پیمانکار',
    valueProposition: 'پیگیری پروژه، صورت‌وضعیت و وصول مطالبات در یک پنل',
    highlights: ['وضعیت مشتریان پروژه‌ای', 'فاکتور مرحله‌ای', 'وظایف تیم اجرایی'],
    salesWalkthroughOrder: 10,
    investorWalkthroughOrder: 10,
    firstStopHref: '/contracting',
    showcaseLinks: [
      { label: 'پیمانکاری', href: '/contracting' },
      { label: 'پروژه‌ها', href: '/contracting/projects' },
      { label: 'فاکتورها', href: '/invoices' },
      { label: 'وظایف', href: '/tasks' },
    ],
  },
  'education-center': {
    id: 'education-center',
    orgSlug: 'demo-education-center',
    title: 'آموزشگاه',
    subtitle: 'آموزشگاه مهارت‌افزا',
    industryPack: 'EDUCATION',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر آموزشگاه',
    valueProposition: 'مدیریت هنرجو، شهریه و پیگیری تماس‌ها در یک فضای کاری',
    highlights: ['هنرجویان فعال', 'شهریه‌های معوق', 'پیگیری ثبت‌نام'],
    salesWalkthroughOrder: 11,
    investorWalkthroughOrder: 11,
    firstStopHref: '/education',
    showcaseLinks: [
      { label: 'آموزشگاه', href: '/education' },
      { label: 'دوره‌ها', href: '/education/courses' },
      { label: 'ثبت‌نام‌ها', href: '/education/enrollments' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'beauty-salon': {
    id: 'beauty-salon',
    orgSlug: 'demo-beauty-salon',
    title: 'سالن زیبایی',
    subtitle: 'سالن زیبایی ماه‌چهره',
    industryPack: 'BEAUTY_SALON',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر سالن',
    valueProposition: 'مدیریت مشتریان وفادار، خدمات و پیگیری مراجعات',
    highlights: ['مشتریان پرتکرار', 'خدمات پرفروش', 'یادآوری مراجعه بعدی'],
    salesWalkthroughOrder: 12,
    investorWalkthroughOrder: 12,
    firstStopHref: '/beauty',
    showcaseLinks: [
      { label: 'سالن زیبایی', href: '/beauty' },
      { label: 'نوبت‌ها', href: '/beauty/appointments' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  restaurant: {
    id: 'restaurant',
    orgSlug: 'demo-restaurant',
    title: 'رستوران',
    subtitle: 'رستوران شبستان',
    industryPack: 'FOOD_SERVICE',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر رستوران',
    valueProposition: 'موجودی مواد اولیه، مشتریان سازمانی و جریان مالی روزانه',
    highlights: ['مواد اولیه رو به اتمام', 'فروش روز', 'پیگیری سفارش‌های سازمانی'],
    salesWalkthroughOrder: 13,
    investorWalkthroughOrder: 13,
    firstStopHref: '/food',
    showcaseLinks: [
      { label: 'غذا و نوشیدنی', href: '/food' },
      { label: 'سفارش‌ها', href: '/food/orders' },
      { label: 'منو', href: '/food/menu' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  cafe: {
    id: 'cafe',
    orgSlug: 'demo-cafe',
    title: 'کافه',
    subtitle: 'کافه روشنه',
    industryPack: 'FOOD_SERVICE',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر کافه',
    valueProposition: 'کنترل اقلام مصرفی، فروش روزانه و مشتریان وفادار',
    highlights: ['مصرف شیر و قهوه', 'فروش روز', 'باشگاه مشتریان'],
    salesWalkthroughOrder: 14,
    investorWalkthroughOrder: 14,
    firstStopHref: '/food',
    showcaseLinks: [
      { label: 'غذا و نوشیدنی', href: '/food' },
      { label: 'سفارش‌ها', href: '/food/orders' },
      { label: 'منو', href: '/food/menu' },
      { label: 'وظایف', href: '/tasks' },
    ],
  },
  bakery: {
    id: 'bakery',
    orgSlug: 'demo-bakery',
    title: 'قنادی و نانوایی',
    subtitle: 'قنادی نان و نبات',
    industryPack: 'FOOD_SERVICE',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر قنادی',
    valueProposition: 'مدیریت سفارشات روز، مواد مصرفی و مشتریان ثابت',
    highlights: ['آرد و کره رو به اتمام', 'سفارش‌های مناسبتی', 'فروش نقدی و اعتباری'],
    salesWalkthroughOrder: 15,
    investorWalkthroughOrder: 15,
    firstStopHref: '/food',
    showcaseLinks: [
      { label: 'غذا و نوشیدنی', href: '/food' },
      { label: 'سفارش‌ها', href: '/food/orders' },
      { label: 'منو', href: '/food/menu' },
      { label: 'گزارش‌ها', href: '/reports' },
    ],
  },
  'mobile-shop': {
    id: 'mobile-shop',
    orgSlug: 'demo-mobile-shop',
    title: 'فروشگاه موبایل',
    subtitle: 'موبایل سنتر پایتخت',
    industryPack: 'RETAIL',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر فروش موبایل',
    valueProposition: 'مدیریت کالاهای گران‌قیمت، مشتریان و فروش اقساطی',
    highlights: ['موجودی مدل‌های پرفروش', 'سفارش مشتری', 'فروش با مانده حساب'],
    salesWalkthroughOrder: 16,
    investorWalkthroughOrder: 16,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'محصولات', href: '/retail/products' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'electronics-store': {
    id: 'electronics-store',
    orgSlug: 'demo-electronics-store',
    title: 'فروشگاه لوازم الکترونیکی',
    subtitle: 'دیجیتال پارس',
    industryPack: 'RETAIL',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر فروش الکترونیک',
    valueProposition: 'کنترل موجودی قطعات و فروش پروژه‌ای به مشتریان سازمانی',
    highlights: ['موجودی قطعات', 'فروش B2B', 'پیگیری استعلام‌ها'],
    salesWalkthroughOrder: 17,
    investorWalkthroughOrder: 17,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'محصولات', href: '/retail/products' },
      { label: 'موجودی', href: '/retail/inventory' },
      { label: 'گزارش‌ها', href: '/reports' },
    ],
  },
  'flower-shop': {
    id: 'flower-shop',
    orgSlug: 'demo-flower-shop',
    title: 'گل‌فروشی',
    subtitle: 'گل‌فروشی بهارستان',
    industryPack: 'RETAIL',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر گل‌فروشی',
    valueProposition: 'مدیریت سفارش روز، اقلام فاسدشدنی و مشتریان مناسبتی',
    highlights: ['گل‌های پرفروش', 'سفارش مراسم', 'یادآوری مشتریان مناسبتی'],
    salesWalkthroughOrder: 18,
    investorWalkthroughOrder: 18,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
      { label: 'وظایف', href: '/tasks' },
    ],
  },
  'pet-shop': {
    id: 'pet-shop',
    orgSlug: 'demo-pet-shop',
    title: 'پت‌شاپ',
    subtitle: 'پت‌شاپ پاپی',
    industryPack: 'RETAIL',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر پت‌شاپ',
    valueProposition: 'مدیریت غذای حیوانات، کالاهای مصرفی و مشتریان دائمی',
    highlights: ['اقلام مصرفی پرتکرار', 'سفارش‌های دوره‌ای', 'مشتریان وفادار'],
    salesWalkthroughOrder: 19,
    investorWalkthroughOrder: 19,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'موجودی', href: '/retail/inventory' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'real-estate': {
    id: 'real-estate',
    orgSlug: 'demo-real-estate',
    title: 'مشاور املاک',
    subtitle: 'املاک آسمان',
    industryPack: 'REAL_ESTATE',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر دفتر املاک',
    valueProposition: 'پیگیری متقاضی، فایل‌ها و کمیسیون در یک پنل متمرکز',
    highlights: ['متقاضیان فعال', 'پیگیری قراردادها', 'وصول کمیسیون'],
    salesWalkthroughOrder: 20,
    investorWalkthroughOrder: 20,
    firstStopHref: '/real-estate',
    showcaseLinks: [
      { label: 'املاک', href: '/real-estate' },
      { label: 'فایل‌ها', href: '/real-estate/listings' },
      { label: 'بازدیدها', href: '/real-estate/showings' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'law-office': {
    id: 'law-office',
    orgSlug: 'demo-law-office',
    title: 'دفتر حقوقی',
    subtitle: 'دفتر حقوقی دادآور',
    industryPack: 'LAW_FIRM',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'وکیل / مدیر دفتر',
    valueProposition: 'مدیریت پرونده مشتری، حق‌الوکاله و پیگیری جلسات',
    highlights: ['موکلان فعال', 'حق‌الوکاله معوق', 'پیگیری جلسات'],
    salesWalkthroughOrder: 21,
    investorWalkthroughOrder: 21,
    firstStopHref: '/law',
    showcaseLinks: [
      { label: 'حقوقی', href: '/law' },
      { label: 'پرونده‌ها', href: '/law/cases' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'accounting-office': {
    id: 'accounting-office',
    orgSlug: 'demo-accounting-office',
    title: 'دفتر حسابداری',
    subtitle: 'حساب‌یاران تراز',
    industryPack: 'ACCOUNTING_FIRM',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر دفتر حسابداری',
    valueProposition: 'پیگیری مشتریان ماهانه، قرارداد خدمات و وصول حق‌الزحمه',
    highlights: ['قراردادهای دوره‌ای', 'سررسید خدمات', 'مطالبات ماهانه'],
    salesWalkthroughOrder: 22,
    investorWalkthroughOrder: 22,
    firstStopHref: '/accounting',
    showcaseLinks: [
      { label: 'حسابداری', href: '/accounting' },
      { label: 'پرونده‌ها', href: '/accounting/matters' },
      { label: 'فاکتورها', href: '/invoices' },
      { label: 'گزارش‌ها', href: '/reports' },
    ],
  },
  gym: {
    id: 'gym',
    orgSlug: 'demo-gym',
    title: 'باشگاه ورزشی',
    subtitle: 'باشگاه انرژی+',
    industryPack: 'FITNESS',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر باشگاه',
    valueProposition: 'مدیریت اعضا، تمدید اشتراک و پیگیری پرداخت‌ها',
    highlights: ['عضویت‌های نزدیک به انقضا', 'پیگیری تمدید', 'گزارش وصول'],
    salesWalkthroughOrder: 23,
    investorWalkthroughOrder: 23,
    firstStopHref: '/fitness',
    showcaseLinks: [
      { label: 'باشگاه', href: '/fitness' },
      { label: 'عضویت‌ها', href: '/fitness/memberships' },
      { label: 'کلاس‌ها', href: '/fitness/classes' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'auto-repair': {
    id: 'auto-repair',
    orgSlug: 'demo-auto-repair',
    title: 'تعمیرگاه خودرو',
    subtitle: 'تعمیرگاه چابک',
    industryPack: 'WORKSHOP',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر تعمیرگاه',
    valueProposition: 'مدیریت مشتریان، سفارش تعمیر و صورتحساب خدمات',
    highlights: ['سفارش‌های در جریان', 'پیگیری تحویل خودرو', 'صورتحساب خدمات'],
    salesWalkthroughOrder: 24,
    investorWalkthroughOrder: 24,
    firstStopHref: '/workshop',
    showcaseLinks: [
      { label: 'تعمیرگاه', href: '/workshop' },
      { label: 'پذیرش‌ها', href: '/workshop/jobs' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  optician: {
    id: 'optician',
    orgSlug: 'demo-optician',
    title: 'عینک‌فروشی و اپتیک',
    subtitle: 'اپتیک دیدآور',
    industryPack: 'RETAIL',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر اپتیک',
    valueProposition: 'مدیریت موجودی فریم، سفارش مشتری و پیگیری تحویل',
    highlights: ['فریم‌های پرفروش', 'سفارش ساخت عدسی', 'تحویل‌های معوق'],
    salesWalkthroughOrder: 25,
    investorWalkthroughOrder: 25,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'محصولات', href: '/retail/products' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'stationery-store': {
    id: 'stationery-store',
    orgSlug: 'demo-stationery-store',
    title: 'لوازم‌التحریر',
    subtitle: 'نوشت‌افزار مهر',
    industryPack: 'RETAIL',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر فروشگاه',
    valueProposition: 'کنترل موجودی کالاهای مصرفی و فروش عمده مدرسه‌ای',
    highlights: ['کالاهای پرفروش فصل', 'سفارش‌های عمده', 'کسری موجودی'],
    salesWalkthroughOrder: 26,
    investorWalkthroughOrder: 26,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'موجودی', href: '/retail/inventory' },
      { label: 'فاکتورها', href: '/invoices' },
      { label: 'وظایف', href: '/tasks' },
    ],
  },
  bookstore: {
    id: 'bookstore',
    orgSlug: 'demo-bookstore',
    title: 'کتاب‌فروشی',
    subtitle: 'کتاب‌فروشی فرهنگ',
    industryPack: 'RETAIL',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر کتاب‌فروشی',
    valueProposition: 'مدیریت عناوین پرفروش، سفارش مجدد و مشتریان سازمانی',
    highlights: ['کتاب‌های پرفروش', 'سفارش ناشران', 'فروش سازمانی'],
    salesWalkthroughOrder: 27,
    investorWalkthroughOrder: 27,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'محصولات', href: '/retail/products' },
      { label: 'گزارش‌ها', href: '/reports' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'hardware-store': {
    id: 'hardware-store',
    orgSlug: 'demo-hardware-store',
    title: 'ابزار و یراق',
    subtitle: 'ابزارسرا',
    industryPack: 'RETAIL',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر ابزارفروشی',
    valueProposition: 'کنترل موجودی ابزار، مشتریان پروژه‌ای و فروش عمده',
    highlights: ['موجودی قطعات کلیدی', 'مشتریان پیمانکاری', 'پیگیری استعلام‌ها'],
    salesWalkthroughOrder: 28,
    investorWalkthroughOrder: 28,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'موجودی', href: '/retail/inventory' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'cosmetics-store': {
    id: 'cosmetics-store',
    orgSlug: 'demo-cosmetics-store',
    title: 'فروشگاه آرایشی',
    subtitle: 'زیبانگار',
    industryPack: 'RETAIL',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر فروشگاه آرایشی',
    valueProposition: 'مدیریت موجودی اقلام آرایشی و مشتریان وفادار',
    highlights: ['محصولات پرفروش', 'مشتریان تکراری', 'هشدار اتمام موجودی'],
    salesWalkthroughOrder: 29,
    investorWalkthroughOrder: 29,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'محصولات', href: '/retail/products' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'وظایف', href: '/tasks' },
    ],
  },
  'tailor-shop': {
    id: 'tailor-shop',
    orgSlug: 'demo-tailor-shop',
    title: 'خیاطی و مزون',
    subtitle: 'مزون نقش',
    industryPack: 'WORKSHOP',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر مزون',
    valueProposition: 'پیگیری سفارش دوخت، تحویل و وصول دستمزد خدمات',
    highlights: ['سفارش‌های در جریان', 'زمان تحویل', 'بیعانه و تسویه'],
    salesWalkthroughOrder: 30,
    investorWalkthroughOrder: 30,
    firstStopHref: '/workshop',
    showcaseLinks: [
      { label: 'تعمیرگاه', href: '/workshop' },
      { label: 'پذیرش‌ها', href: '/workshop/jobs' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'jewelry-store': {
    id: 'jewelry-store',
    orgSlug: 'demo-jewelry-store',
    title: 'طلافروشی و جواهری',
    subtitle: 'جواهری زرین',
    industryPack: 'RETAIL',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر جواهری',
    valueProposition: 'کنترل موجودی کالاهای ارزشمند و فروش به مشتریان خاص',
    highlights: ['کالاهای پرفروش', 'مشتریان VIP', 'سفارش‌های ویژه'],
    salesWalkthroughOrder: 31,
    investorWalkthroughOrder: 31,
    firstStopHref: '/retail',
    showcaseLinks: [
      { label: 'داشبورد فروشگاه', href: '/retail' },
      { label: 'محصولات', href: '/retail/products' },
      { label: 'گزارش‌ها', href: '/reports' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'cleaning-services': {
    id: 'cleaning-services',
    orgSlug: 'demo-cleaning-services',
    title: 'خدمات نظافتی',
    subtitle: 'پاک‌خانه',
    industryPack: 'CLEANING',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر خدمات',
    valueProposition: 'برنامه‌ریزی سفارش‌ها، پیگیری مشتری و صدور صورتحساب خدمات',
    highlights: ['سفارش‌های امروز', 'تیم‌های اعزامی', 'وصول خدمات'],
    salesWalkthroughOrder: 32,
    investorWalkthroughOrder: 32,
    firstStopHref: '/cleaning',
    showcaseLinks: [
      { label: 'نظافت', href: '/cleaning' },
      { label: 'سفارش‌ها', href: '/cleaning/jobs' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'marketing-agency': {
    id: 'marketing-agency',
    orgSlug: 'demo-marketing-agency',
    title: 'آژانس بازاریابی',
    subtitle: 'رشدنو',
    industryPack: 'MARKETING_AGENCY',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر آژانس',
    valueProposition: 'مدیریت مشتریان ریتینری، پروژه‌ها و وصول صورت‌حساب ماهانه',
    highlights: ['قراردادهای فعال', 'تحویل‌دادنی‌ها', 'صورتحساب ماهانه'],
    salesWalkthroughOrder: 33,
    investorWalkthroughOrder: 33,
    firstStopHref: '/agency',
    showcaseLinks: [
      { label: 'بازاریابی', href: '/agency' },
      { label: 'کمپین‌ها', href: '/agency/campaigns' },
      { label: 'گزارش‌ها', href: '/reports' },
      { label: 'اتوماسیون', href: '/automation' },
    ],
  },
  'printing-shop': {
    id: 'printing-shop',
    orgSlug: 'demo-printing-shop',
    title: 'چاپ و تبلیغات',
    subtitle: 'چاپ‌خانه رنگین',
    industryPack: 'PRINTING',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر چاپخانه',
    valueProposition: 'پیگیری سفارش چاپ، تحویل و تسویه پروژه‌های تبلیغاتی',
    highlights: ['سفارش‌های آماده تحویل', 'پیگیری چاپ', 'تسویه پروژه'],
    salesWalkthroughOrder: 34,
    investorWalkthroughOrder: 34,
    firstStopHref: '/printing',
    showcaseLinks: [
      { label: 'چاپ', href: '/printing' },
      { label: 'سفارش‌ها', href: '/printing/orders' },
      { label: 'وظایف', href: '/tasks' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'insurance-agency': {
    id: 'insurance-agency',
    orgSlug: 'demo-insurance-agency',
    title: 'نمایندگی بیمه',
    subtitle: 'بیمه‌یار',
    industryPack: 'INSURANCE_AGENCY',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر نمایندگی بیمه',
    valueProposition: 'مدیریت مشتریان، تمدید بیمه‌نامه و پیگیری اقساط',
    highlights: ['بیمه‌نامه‌های نزدیک تمدید', 'اقساط معوق', 'پیگیری مشتریان'],
    salesWalkthroughOrder: 35,
    investorWalkthroughOrder: 35,
    firstStopHref: '/insurance',
    showcaseLinks: [
      { label: 'بیمه', href: '/insurance' },
      { label: 'بیمه‌نامه‌ها', href: '/insurance/policies' },
      { label: 'گزارش‌ها', href: '/reports' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'appliance-repair': {
    id: 'appliance-repair',
    orgSlug: 'demo-appliance-repair',
    title: 'تعمیرات لوازم خانگی',
    subtitle: 'خانه‌ساز سرویس',
    industryPack: 'WORKSHOP',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر خدمات تعمیرات',
    valueProposition: 'ثبت سفارش تعمیر، پیگیری تکنسین و صورتحساب خدمات',
    highlights: ['درخواست‌های باز', 'تکنسین‌های اعزامی', 'وصول خدمات'],
    salesWalkthroughOrder: 36,
    investorWalkthroughOrder: 36,
    firstStopHref: '/workshop',
    showcaseLinks: [
      { label: 'تعمیرگاه', href: '/workshop' },
      { label: 'پذیرش‌ها', href: '/workshop/jobs' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'photography-studio': {
    id: 'photography-studio',
    orgSlug: 'demo-photography-studio',
    title: 'آتلیه عکاسی',
    subtitle: 'آتلیه نور',
    industryPack: 'PHOTOGRAPHY',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر آتلیه',
    valueProposition: 'مدیریت رزرو، پیگیری تحویل آلبوم و تسویه خدمات',
    highlights: ['رزروهای هفته', 'تحویل‌های عقب‌افتاده', 'بیعانه و مانده'],
    salesWalkthroughOrder: 37,
    investorWalkthroughOrder: 37,
    firstStopHref: '/photography',
    showcaseLinks: [
      { label: 'عکاسی', href: '/photography' },
      { label: 'جلسات', href: '/photography/sessions' },
      { label: 'وظایف', href: '/tasks' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'daycare-center': {
    id: 'daycare-center',
    orgSlug: 'demo-daycare-center',
    title: 'مهدکودک',
    subtitle: 'مهد ستاره‌ها',
    industryPack: 'EDUCATION',
    planCode: 'STARTER',
    planLabel: 'استارتر',
    personaTitle: 'مدیر مهدکودک',
    valueProposition: 'مدیریت والدین، شهریه و پیگیری ثبت‌نام و تمدید',
    highlights: ['شهریه‌های معوق', 'ظرفیت ثبت‌نام', 'پیگیری خانواده‌ها'],
    salesWalkthroughOrder: 38,
    investorWalkthroughOrder: 38,
    firstStopHref: '/education',
    showcaseLinks: [
      { label: 'آموزشگاه', href: '/education' },
      { label: 'دوره‌ها', href: '/education/courses' },
      { label: 'ثبت‌نام‌ها', href: '/education/enrollments' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'computer-service': {
    id: 'computer-service',
    orgSlug: 'demo-computer-service',
    title: 'خدمات کامپیوتری',
    subtitle: 'فناوران سیستم',
    industryPack: 'WORKSHOP',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر خدمات IT',
    valueProposition: 'مدیریت قراردادهای پشتیبانی، تیکت‌های حضوری و صورتحساب دوره‌ای',
    highlights: ['مشتریان قراردادی', 'کارهای باز', 'فاکتورهای ماهانه'],
    salesWalkthroughOrder: 39,
    investorWalkthroughOrder: 39,
    firstStopHref: '/workshop',
    showcaseLinks: [
      { label: 'تعمیرگاه', href: '/workshop' },
      { label: 'پذیرش‌ها', href: '/workshop/jobs' },
      { label: 'مشتریان', href: '/customers' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
  'veterinary-clinic': {
    id: 'veterinary-clinic',
    orgSlug: 'demo-veterinary-clinic',
    title: 'کلینیک دامپزشکی',
    subtitle: 'دامپزشکی مهربان',
    industryPack: 'CLINIC',
    planCode: 'BUSINESS',
    planLabel: 'حرفه‌ای',
    personaTitle: 'مدیر کلینیک دامپزشکی',
    valueProposition: 'مدیریت نوبت، پرونده حیوانات و پیگیری درمان در یک هسته واحد',
    highlights: ['نوبت‌های امروز', 'پرونده حیوانات', 'یادآوری واکسن و ویزیت'],
    salesWalkthroughOrder: 40,
    investorWalkthroughOrder: 40,
    firstStopHref: '/clinic',
    showcaseLinks: [
      { label: 'داشبورد کلینیک', href: '/clinic' },
      { label: 'نوبت‌ها', href: '/clinic/appointments' },
      { label: 'بیماران', href: '/clinic/patients' },
      { label: 'فاکتورها', href: '/invoices' },
    ],
  },
};

const SPECIALTY_DEMO_SCENARIOS: Record<string, DemoScenario> = Object.fromEntries(
  listSpecialties()
    // Curated BASE scenarios win for the same specialty id (e.g. medical-office, pharmacy).
    .filter((specialty) => !(specialty.id in BASE_DEMO_SCENARIOS))
    .map((specialty, index) => [
      specialty.id,
      {
        id: specialty.id as DemoScenarioId,
        orgSlug: `demo-spec-${specialty.id}`,
        title: specialty.label,
        subtitle: `دمو ${specialty.label}`,
        industryPack: specialty.basePack,
        planCode: 'STARTER',
        planLabel: 'استارتر',
        personaTitle: `مدیر ${specialty.label}`,
        valueProposition: specialty.description,
        highlights: specialty.tips.slice(0, 3),
        salesWalkthroughOrder: 100 + index,
        investorWalkthroughOrder: 100 + index,
        firstStopHref: specialty.homePath,
        showcaseLinks: [
          { label: specialty.label, href: specialty.homePath },
          { label: specialty.labels.customers, href: '/customers' },
          { label: 'فاکتورها', href: '/invoices' },
        ],
      } satisfies DemoScenario,
    ]),
);

export const DEMO_SCENARIOS = {
  ...SPECIALTY_DEMO_SCENARIOS,
  ...BASE_DEMO_SCENARIOS,
} as Record<DemoScenarioId, DemoScenario>;

export const DEMO_SCENARIO_LIST = Object.values(DEMO_SCENARIOS).sort(
  (a, b) => a.salesWalkthroughOrder - b.salesWalkthroughOrder,
);

export const DEMO_INVESTOR_ORDER = Object.values(DEMO_SCENARIOS).sort(
  (a, b) => a.investorWalkthroughOrder - b.investorWalkthroughOrder,
);

export function getScenarioById(id: string): DemoScenario | undefined {
  return DEMO_SCENARIOS[id as DemoScenarioId];
}

export function getScenarioByOrgSlug(slug: string): DemoScenario | undefined {
  return DEMO_SCENARIO_LIST.find((s) => s.orgSlug === slug);
}

export function getScenarioIdByOrgSlug(slug: string): DemoScenarioId | null {
  const s = getScenarioByOrgSlug(slug);
  return s?.id ?? null;
}
